serverless/test

.travis.yml
README.md
bin/mocha-isolated.js
configure-inquirer-stub.js
disable-serverless-stats-requests.js
docs/bin/mocha-isolated.md
docs/configure-inquirer-stub.md
docs/disable-serverless-stats-requests.md
docs/process-tmp-dir.md
docs/run-serverless.md
docs/setup/async-leaks-detector.md
docs/setup/mock-homedir.md
docs/setup/restore-cwd.md
docs/skip-on-disabled-symlinks-in-windows.md
docs/skip-with-notice.md
lib/private/rm-tmp-dir-ignorable-error-codes.js
package.json
process-tmp-dir.js
run-serverless.js
setup/async-leaks-detector/bluebird-patch.js
setup/async-leaks-detector/index.js
setup/mocha-reporter.js
setup/mocha-reporter.test.js
setup/mock-homedir.js
setup/restore-cwd.js
skip-on-disabled-symlinks-in-windows.js
skip-with-notice.js

Covers all setup, scripts and utils, currently implemented in serverless repository, but of which we want to take advantage in other projects.
Migration PR's in project which will depend on it:
_(Temporararily they link a github repo as dependency in `package.json`)_
- https://github.com/serverless/serverless/pull/6660
- https://github.com/serverless/enterprise-plugin/pull/262 (this one reports CI fail, purely because of "dropped" coverage, and that is result of a difference in how Jest and NYC reports a coverage (NYC seems to do it better) - I'll explain that in that PR)

Initial implementation

---

setup/mock-homedir.js

It was cleaned after every suite (describe) ended and that produced  fails in cases where parent suite was pursuing some homedir setup

Cleanup homedir only after top suite ends

---

docs/run-serverless.md
run-serverless.js

- Introduce `hooks` option. To enable some injections into preconfigured mocked environment
- (breaking) Rename  `hookNamesWhiteList` into `lifecycleHookNamesWhitelist`, so it's not (easily) confused with `hooks` option,

Support hooks in run-serverless util

---

commitlint.config.js
docs/run-serverless.md
package.json
run-serverless.js

Configuring `runServerless` can be challenging (especially at the beginning).
Provided validation should pick most common errors and output valuable hints that should help to understand and address discovered issues
Tested against all tests that rely on this util (in `serverless` and `@serverless/enterprise-plugin`)

Extensive options validation for runServerless util

---

docs/provision-tmp-dir.md
docs/run-serverless.md
provision-tmp-dir.js
run-serverless.js

`config` option, as an alternative to `cwd`. Thanks to it, in simple cases (where we test purely against serverless config), there's no need to manually create a service fixture directory.
Additionally configured a `provision-tmp-dir` utility.

Run Serverless: Support `config` option

---

commitlint.config.js
configure-inquirer-stub.js

Needed in context of https://github.com/serverless/serverless/pull/6835, where we directly run a [tabtab's inquirer prompt](https://github.com/mklabs/tabtab/blob/8e16e476331777a33b2b04fa913644c52f63b328/lib/prompt.js).
- Support multiple prompts in fake `inquirer.prompt` stub
- Ensure to mock `createPromptModule`
- Make handling of stubs easier, and automatically reset previous stub on new stub initialization

Extend functionality of configure-inquirer-stub

---

docs/setup/log.md
package.json
setup/log.js

Attaches [log](https://github.com/medikoo/log-node#log-node) writer which by default flushes all observed logs (down to _debug_ level) in case of test failure.
It's about logs written with [log](https://github.com/medikoo/log#log) utility, and in case of our project [child-process-ext/spawn](https://github.com/medikoo/child-process-ext/blob/master/spawn.js) logs all std output from invoked processes.
This functionality provides reliable means to debug unexpected test failures, as then if eventual spawned processes were run via `child-process-ext/spawn`, their output will be exposed in terminal in such case.
Needed for https://github.com/serverless/serverless/pull/6867

Extension to output gathered logs on test failure

---

docs/run-serverless.md
package.json
resolve-env.js
run-serverless.js

- Ensure not to accidentally assign `undefined` as env vars
- Validate input `env`
- Support `envVarNamesWhitelist` option

Improve env handling in runServerless

---

commitlint.config.js
setup/log.js

In gathered log debug output (which is output after eventual test fail), test boundaries may not be perfectly clear.
Adding logs that indicate when given _describe_ or _it_ execution starts will solve that problem

Test log markers

---

bin/mocha-isolated.js
commitlint.config.js

- Do not hard crash on first test fail (after all test finalize write short summary on failure)
- Provide support for gentle `--bail` option, which will not propagate any further tests after first fail (and after all tests run will write a short summary on failures)
- Provide in sync dump of stdout and stderr from tests runs (seing first stdout and then stderr was not that natural)

Mocha isolated improvements

---

setup/async-leaks-detector/index.js

As with current settings false positives were observed, e.g.: https://travis-ci.org/serverless/serverless/jobs/585463694

Increase async leaks detector wait gap

---

docs/run-serverless.md
run-serverless.js

- Replace _whitelist_ approach with _blacklist_ one. Reasoning:
- Ensuring that all registered hooks are run instead of few picked, makes tests more reliable as it'll pick eventual breaking side effects as introduced by changes to other (not being in scope of given tests) plugins.
- Additionally it'll make configuration significantly easier. Finding which hooks and plugin should be whitelisted for given scope, to have it properly tested is not trivial in many cases.
- Expose current, resolved context to hooks

Improvements to run-serverless util

---

docs/setup/restore-env.md
setup/restore-env.js

When debugging windows Ci fail: https://travis-ci.org/serverless/serverless/jobs/623668512
I've found out that some tests leave `process.env` altered. It may influence the test results in tests that follow (it might that it's the reason behind above CI fail).
Like we already have `restoreCwd` util, that reverts eventually changed `cwd` to initial state.
This PR introduces `restoreEnv` util, that does same to `process.env`

`restore-env` mocha setup extension

---

CHANGELOG.md
bin/mocha-isolated.js
docs/bin/mocha-isolated.md
package.json

I've noticed that Travis in [serverless](https://github.com/serverless/serverless/) always runs integration tests one by one (no concurrent runs). It's due to fact, that only one CPU core is provided for test run (so technically it behaves as expected).
Still in case of this tests we do a lot of network calls, so introducing a concurrency will definitely speed up a build time, which becomes quite long (we already reached maximum allowed time of 50 minutes by Travis: https://travis-ci.org/serverless/serverless/jobs/624151922)
Before splitting tests into multiple jobs, it'll be good to explore how things will get improved with enforced concurrency, and this patch will allow us to configure that.
--- 
Additionally improved `moha-isolated` setup with `minimist`, and included a release commit

Support custom concurrency in Mocha Isolated

---

CHANGELOG.md
bin/mocha-isolated.js
package.json

Didn't expose when no path arguments were passed.

Fix accidentally broken CLI args validation in mocha-isolated

---

CHANGELOG.md
bin/mocha-isolated.js
package.json
setup/async-leaks-detector/index.js

It's to address issues exposed with: https://travis-ci.org/serverless/serverless/builds/624572785
- Mocha isolated: To avoid confusing error output, do not hard crash on any exit code of child process
- Async leaks detector: Increase timeout to avoid false positives

Mocha isolated and async leaks detector improvements

---

CHANGELOG.md
package.json
setup/log.js

For CI fails investigation it's also great to know the exact time at which given event happen, and timespan between events.
This patch ensures timestamps will be exposed.

Logs: Ensure timestamps by logs

---

CHANGELOG.md
aws-request.js
docs/aws-request.md
package.json
resolve-aws-env.js
resolve-env.js

- Recognize dashboard specific test debug env vars
- Seclude `awsRequest` from [serverless](https://github.com/serverless/serverless/blob/de887ac23a1fbb3f68ea64f16c13c02d75c21932/tests/utils/misc/index.js#L15-L39), so we can rely on it also in `@serverless/enterprise-plugin`

Dashboard related improvements

---

.travis.yml

Deploy failed with `missing api_key` error, while API key is configured https://travis-ci.org/serverless/test/builds/639477577
It appears as known Travis CI  issue, workaround it so add `edge: true` to deploy config.
In a meantime I've published v3.5.0 manually

CI: Workaround Travis CI issue

---

setup/mocha-reporter.js
setup/mock-homedir.js

Run into scenario where test timeout fail propagated few other crashes, and in result provided output was clueless.
This patch ensures that all errors are exposed in such case and process exits with non `0` code

Fix Mocha patches

---

commitlint.config.js
setup/async-leaks-detector/index.js

False positive was observed in this CI fail: https://travis-ci.com/serverless/enterprise-plugin/jobs/289444390

Bump timeout in async leaks detector to avoid false positives

---

configure-aws-request-stub.js
docs/configure-aws-request-stub.md
docs/run-serverless.md
package.json
run-serverless.js

- `configureAwsRequestStub` - Stub AWS requests with preconfigured mocks map
- `lastLifecycleHookName` option (allows to stop lifecycle engine at some point)
- `awsRequestStubMap` option to automate stubbing of AWS requests
- `shouldStubSpawn` option, to make any child_process spawn's, as made via `child-process-ext/spawn` ineffective.
Additionally ensure no sync exceptions in `runServerless` util

runServerless improvements

---

commitlint.config.js
docs/has-failed.md
has-failed.js

Answers whether any tests in passed suite failed. Useful when we want to abort cleanup in after after a test fail, to enable further investigation.

Mocha `hasFailed` util

---

commitlint.config.js
docs/run-serverless.md
run-serverless.js

Comes with a breaking change, as `runServerless` no longer resolves `serverless` instance directly. Now data object is returned with `serverless` and `stdoutData` properties

Run Serverless: Mute stdout and expose at stdoutData

---

configure-aws-request-stub.js
docs/configure-aws-request-stub.md

Per discussion at https://github.com/serverless/serverless/pull/8351#issuecomment-705826049 this change will allow AWS request stubs to be either scalars or functions allowing use cases like:
```js
runServerless({
// ...
awsRequestStubMap: {
// ...
S3: {
// **NEW**: Allow different responses for different calls!
headObject: sandbox.stub()
.onCall(0).returns({
Metadata: { filesha256: 'FIRST_VALUE' }
})
.onCall(1).returns({
Metadata: { filesha256: 'SECOND_VALUE' }
}),
// **OLD**: Scalars still work
listObjectsV2: {
Contents: [
{
Key:
'serverless/test-package-artifact/dev/1589988704359-2020-05-20T15:31:44.359Z/compiled-cloudformation-template.json',
LastModified: new Date(),
ETag: '"5102a4cf710cae6497dba9e61b85d0a4"',
Size: 356,
StorageClass: 'STANDARD',
},
{
Key: …
```

Feature: Allow functions as AWS provider request stubs.

---

lib/private/rm-tmp-dir-ignorable-error-codes.js

Observed, after recent changes, in Windows CI build: https://github.com/serverless/serverless/pull/8428/checks?check_run_id=1297905115

Recognize EBUSY as safe to ignore on cleanup of tmp dir

---

setup/mocha-reporter.js

Fix, to workaround race condition as diagnosed at https://github.com/serverless/serverless/pull/8413#issuecomment-732265708 (cc @pgrzesik)
Interestingly, in some race condition scenarios `then` callbacks as attached to [`deferredRunner`](https://github.com/serverless/test/blob/2deb709ada86ec400c8d2358a14c37adf5bd25ee/setup/mocha-reporter.js#L52)
are propagated after first test is being executed (it's influenced by patch  which changes scheduling of tests to be propagated via `process.nextTick` instead of `setImmediate`).
It most likely goes down to how V8 propagates promises callbacks, which can differ in some scenarios, e.g. when invoking mocha via `npx` (as `npx mocha test.js`), the promise callbacks were propagated before first test, while when invoking the mocha binary directly (via …

Mocha Fixes: Fix tests propagation patch

---

setup/patch.js

Workaround for https://github.com/mochajs/mocha/issues/4552 
This patch ensures that eventual circular references in array won't crash Mocha in parallel mode. It won't prevent hang in case error cross-references to its own instance, but I take we don't have to worry about this scenario at this point.
Confirmed to have no effect when no _parallel_ processing is applied

feat(Mocha): Patch circular references parallel invocation bug

---

run-serverless.js

Follow up to https://github.com/serverless/serverless/pull/8801 which introduces `configuration` option to `Serverless` constructor.
Update is not breaking, it's purely about ensuring `configuration` for `serverless` versions which support it.

Run Serverless: Support new "configuration" option

---

setup/log.js

We're battling the error that happens in CI environment, and recently it went without stack trace being logged. Simply because Mocha logs stack trace only in final summary, and it appears that process was terminated before that summary was printed.
(CI fail in question: https://github.com/serverless/serverless/runs/1813369649)
This patch ensures that test fail is logged right when it happens and is registered by Mocha as fail.

Mocha: Log test error right when it happens

---

run-serverless.js

I've noticed that all tests that depend on calling `monitorStack` in `serverless/serverless` are taking longer time due to the fact that default value of monitoring frequency is set to 5 seconds (so they will take at least 5 seconds extra for each call to `monitorStack`). Reference: https://github.com/serverless/serverless/blob/a11a43c5d2d770ca2df849408dad10fe6de95c38/lib/plugins/aws/lib/monitorStack.js#L17

feat: Ensure monitoring frequency is low to speed up tests

---

process-tmp-dir.js

In some systems (as macOS) `os.tmpdir()` points symlinked path, relying on which may raise issues in some testing scenarios (e.g. when confirming on path).
Recently with extensions to lambda image support, we've added tests that confirm on tmp path, and I found them failing on macOS as:
It's due to `os.tmpdir()` resolving `/var/folders/...` path to tmpdir, while `/var` on macOS is a symlink to `/private/var`.
This patch ensures we always work with real paths when tmp dirs are concerned

Ensure to expose real tmp dir path

---

run-serverless.js

Follow up to https://github.com/serverless/serverless/pull/8927. Needed to be merged and released for the https://github.com/serverless/serverless/pull/8927 to pass tests.

Run Serverless: Adapt to a new CLI parser

---

docs/run-serverless.md
run-serverless.js

Complement to https://github.com/serverless/serverless/pull/8987, with provided ability to fallback to the old parser

Run Serverless: Resolve variables with a new resolver

---

docs/run-serverless.md
run-serverless.js

After https://github.com/serverless/serverless/issues/8364 been addressed. It's more natural to initialize instance directly with `commands` and `options` and do not mimic CLI environment.
Drop `cliArgs` in favor of `command` and `options`, breaking change.
Closes #88

Upgrade `runServerless` to more programmatic approach

---

disable-serverless-stats-requests.js

Previous PR had a buggy implementation that didn't properly resolve path to module :sweat:

fix: Resolution of analytics module

---

setup/patch.js

This patch ensures that if tested project shares difference instance of Mocha than `@serverless/test`, it's the tested project Mocha instance that's patched, and not one at `@serverless/test` (patching different instance is ineffective)

Mocha: Ensure to resolve `Mocha` local to tested package

---

resolve-env.js
setup-fixtures-engine.js
setup/patch.js

When new deprecation is introduced, ideally all tests should be updated to not rely on deprecated functionality (unless we're testing it specifically).
Unfortunately, as we didn't have good validation mean to detect such usage, a lot of tests that rely on deprecated functionalities were left not updated.
Now, with https://github.com/serverless/serverless/pull/9623 it'll be possible to have deprecations reported as errors. This PR ensures it'll be the case by default for test run in Serverless projects.
Additionally I've set environment variable guarding telemetry reports not to be send.
In https://github.com/serverless/serverless/pull/9623 and https://github.com/serverless/dashboard-plugin/pull/600 I've ensured that both `serverless` and `dashboard-plugin` are prepared for that change …

Enforce error deprecations mode

---

.github/workflows/integrate.yml
resolve-env.js

It's helpful when debugging to let all debug logs flow, yet in `mocha-isolated` run `LOG_LEVEL` env var was not passed down stream. This patch fixes that.
Additionally cleanuped up commit range resolution in CI

Pass through `LOG_LEVEL` env variable

---

setup-fixtures-engine.js

Unfortuntely https://github.com/serverless/test/pull/115 introduced regression.
Interestingly observable only on Windows https://github.com/serverless/serverless/runs/4235343385?check_suite_focus=true
There are edge cases where we test fixtures with empty configuration file, and handling of that case was changed with refactor. This patch fixes that

Fixtures Engine: Fix handling of fixtures with no config

---

commitlint.config.js
resolve-aws-env.js

So e.g. `SERVERLESS_PLATFORM_STAGE` is passed through

Environment: Allow env vars starting with `SERVERLESS_PLATFORM_`

---

resolve-env.js

Needed for allowing to tweak the cache directory of compiled schema validation code
Related: https://github.com/serverless/serverless/pull/10429

feat: Add schema cache env var to allowlist

---

README.md
aws-request.js
docs/aws-request.md
package.json

To open door for upgrading to AWS SDK v3, I needed to introduce a breaking change in `awsRequest` util. Therefore this will trigger v10 release.
I've tested new `awsRequest` with `serverless` where it's used in integration tests. It can be used against both `aws-sdk` v2 and v3. 
In context of v9 I've also forgot to upgrade mocha to v9, here it's also applied as a breaking change

Upgrade dependencies

---

resolve-env.js

Reported internally, Github Actions Windows Runner specifies temporary directory returned by `os.tmpdir` in `TEMP`.

fix: Add `TEMP` to `resolve-env` whitelist

---

bin/mocha-isolated.js

Path to Mocha binary is hardcoded with assumption that Mocha is always installed in current working directory `node_modules.
It may not be the case with multi package repository, where top-level `node_modules` may host `mocha`.
This patch ensures, Mocha is resolved properly in such scenarios

Mocha Isolated: Fix resolution of Mocha binary

---

aws-request.js
commitlint.config.js

SDK v3 returns promises by default, there's no `promise()` method available

AWS Request: Fix handling of AWS SDK v3 responses

---

docs/setup-run-serverless-fixtures-engine.md

Some links in the documentation where broken since they were still referencing the old file get-fixtures-engine.md.
They now point to the existing file setup-fixtures-engine.md.

docs: Fix broken links after rename to `setup-fixtures-engine`

---

.github/workflows/integrate.yml
.github/workflows/publish.yml
.github/workflows/validate.yml
package.json

Add support for `mocha@10`.
Additionally, it makes the peer dependency on `mocha` optional, because the hooks provided for mocha aren't used in all cases.
I changed `integration.yml` to use a matrix to test both on `mocha@10` and `mocha@9` and their respective node versions too

Add support for mocha 10

---

aws-request.js

Follow up to CI fail caused by `Too Many Requests` error

fix(AWS Request): Retry on `Too Many Requests` error
