serverless/test

configure-inquirer-stub.js
- Improve error reporting
- Support validation for `password` type
=> Improve inquirer stub configurator

bin/mocha-isolated.js, docs/resolve-aws-env.md, docs/resolve-env.md, resolve-aws-env.js, resolve-env.js
Utils that allow to resolve deterministic environment for process runs, which are unaffected by environment in which tests are run.
Needed for https://github.com/serverless/serverless/pull/6867
=> Reusable deterministic env resolvers

setup/log.js
- On test failure do not flush logs if there are just Mocha logs, as in such case it's just invaluable noise
- Improve message of Mocha log
=> Improve handling of Mocha logs

resolve-env.js
So it's passed through to isolated tests
=> Ensure to whitelist SERVERLESS_BINARY_PATH env var

.travis.yml, package.json
Apply same improvements, as those recently applied in [serverless](https://github.com/serverless/serverless/)
=> CI improvements

resolve-aws-env.js
It's to automatically whitelist any newly introduced
=> Ensure to whitelist all SERVERLESS_PLATFORM_TEST_* env vars

run-serverless.js
Should have been updated together with 8238bfd4d7eaf5cbadfb0b5930493663fc19d66a
=> Run Serverless: Fix handling of `shouldStubSpawn` option

run-serverless.js
Addresses issues exposed here: https://github.com/serverless/enterprise-plugin/pull/516/checks?check_run_id=1353606446
=> Run Serverless: Fix absolute module paths handling on Windows

package.json, setup-fixtures-engine.js
Closes: https://github.com/serverless/serverless/issues/8627
Should be merged after https://github.com/serverless/utils/pull/66
=> Add @serverless/utils dependency and use AWS specific YAML schema

run-serverless.js
Follow up to https://github.com/serverless/serverless/pull/8770 which introduces `configurationPath` option to `Serverless` constructor.
Update is not breaking, it's purely about ensuring `configurationPath` for `serverless` versions which support it.
=> Run Serverless: Support new "configurationPath" option

docs/run-serverless.md, run-serverless.js
Needed for https://github.com/serverless/serverless/issues/8886
=> Run Serverless: `beforeInstanceInit` hook

run-serverless.js
Follow up to https://github.com/serverless/serverless/pull/9040
Can be merged independently and doesn't block above PR
=> Run Serverless: Pass "isConfigurationResolved" to constructor

CHANGELOG.md, package.json
Additionally improve changelog generation config, so maintenance updates are also automatically included
=> Release v7.10.1

run-serverless.js
Complement https://github.com/serverless/serverless/pull/9181
=> Run Serverless: Resolve commands with schema

disable-serverless-stats-requests.js
Needed for https://github.com/serverless/serverless/issues/9257 and refactoring to `telemetry` from `analytics`
=> feat: Add support for analytics disable module in `telemetry` dir

run-serverless.js
Adapt to changes introduced with https://github.com/serverless/serverless/pull/9307
=> Run Serverless: Pass `serviceDir` and `configurationFilename`

setup-fixtures-engine.js
Retry on npm install error (as observed randomly in CI: https://github.com/serverless/serverless/runs/2964603919?check_suite_focus=true)
=> Fixture engine improvements

run-serverless.js
It wasn't with overriden modules cache.
Discovered when working on https://github.com/serverless/serverless/pull/9769
=> Run Serverless: Ensure CLI input resolution patch is applied

run-serverless.js
To be able to inject into lifecycles hook resolution internal resolution within Framework was updated with new logic that's responsible for hooks running and resolution. This broken support for some options as `lastLifecycleHookName` in `runServelress`
This PR brings support for new internal hooks resolver
=> Run Serverless: Support new internal hooks resolution

setup-fixtures-engine.js
Done when debugging Node.js v16 problem observed CI. It'll be good to have that in permanently
=> Fixtures Engine: Refactor to async/await

docs/run-serverless.md, run-serverless.js
Needed for dashboard plugin variables test refactor
=> Run Serverless: Introduce `beforeInstanceRun` hook

disable-serverless-stats-requests.js
Follows https://github.com/serverless/serverless/pull/10563
=> Update to rename changes on `serverless` side

configure-inquirer-stub.js
Improve validation of list style values
=> Inquirer Stub: Improve reliability
